import os
import datetime


def save_document(response_text: str, directory: str = "./output") -> str:
    """Export travel plan to a Markdown file with proper formatting."""
    if not response_text or not response_text.strip():
        raise ValueError("Response text is empty — nothing to save.")

    os.makedirs(directory, exist_ok=True)

    now = datetime.datetime.now()
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S")
    human_time = now.strftime("%Y-%m-%d at %H:%M")

    markdown_content = f"""# 🌍 AI Travel Plan

**Generated:** {human_time}  
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""

    try:
        filename = os.path.join(directory, f"AI_Trip_Planner_{timestamp}.md")

        with open(filename, "w", encoding="utf-8") as f:
            f.write(markdown_content)

        print(f"Markdown file saved as: {filename}")
        return filename

    except Exception as e:
        raise RuntimeError(f"Error saving markdown file: {e}") from e
